# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

home:
  path: /
  controller: App\Controller\HomeController::index

eleves:
  path: /eleves
  controller: App\Controller\EleveController::index

eleves.show:
  path: /eleves/{login}-{id}
  controller: App\Controller\EleveController::show

eleves.edit:
  path: /eleves/edit/{id}
  controller: App\Controller\EleveController::edit

eleves.new:
  path: /eleves/create
  controller: App\Controller\EleveController::new

eleves.delete:
  path: /eleves/delete/{id}
  controller: App\Controller\EleveController::delete

evaluations:
  path: /evaluations
  controller: App\Controller\EvaluationController::index
